// tetris-vue/src/infrastructure/ui/components/App.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

import TetrisBoard from "./TetrisBoard.vue";
import GameOverDialog from "./GameOverDialog.vue";
import { BoardService } from "../../../domain/services/services.ts";
import { Board } from "../../../domain/models/board";

const setBoard = (newBoard: Board) => {
  board.value = newBoard;
  tick.value++;
};

const board = ref<Board>(BoardService.getInitialBoard());
const tick = ref(0);

onMounted(() => {
  setInterval(() => {
    if (board.value.status === "game-over") return;
    setBoard(BoardService.moveCurrentBlockDown(board.value));
  }, 1000);
});

onMounted(() =>
  document.addEventListener("keydown", (event: KeyboardEvent) => {
    if (board.value.status === "game-over") return;

    if (event.key === "ArrowLeft") setBoard(BoardService.moveCurrentBlockLeft(board.value));
    else if (event.key === "ArrowRight") setBoard(BoardService.moveCurrentBlockRight(board.value));
    else if (event.key === "ArrowDown") setBoard(BoardService.moveCurrentBlockDown(board.value));
    else if (event.key === "ArrowUp") setBoard(BoardService.rotateCurrentBlock(board.value));
    else if (event.key === "Enter") setBoard(BoardService.moveCurrentBlockDown(board.value, true));
  })
);
</script>

<template>
  <div class="p-6 md:p-10 bg-blue-300 h-screen relative">
    <TetrisBoard :board="board" :key="tick" />
    <GameOverDialog
      v-if="board.status === 'game-over'"
      :score="board.score"
      :onRestart="() => setBoard(BoardService.getInitialBoard())"
    />
  </div>
</template>

<style scoped></style>

// tetris-angular/src/infrastructure/ui/app/app.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import { interval } from 'rxjs';
import { BoardService } from 'src/domain/services/services';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  board = BoardService.getInitialBoard();

  ngOnInit(): void {
    interval(1000).subscribe((tick) => {
      if (this.board.status === 'game-over') return;
      this.board = BoardService.moveCurrentBlockDown(this.board);
    });
  }

  onRestart(): void {
    this.board = BoardService.getInitialBoard();
  }

  @HostListener('document:keydown', ['$event'])
  messageListener({ key }: KeyboardEvent): void {
    if (key === 'ArrowLeft') this.board = BoardService.moveCurrentBlockLeft(this.board);
    else if (key === 'ArrowRight') this.board = BoardService.moveCurrentBlockRight(this.board);
    else if (key === 'ArrowDown') this.board = BoardService.moveCurrentBlockDown(this.board);
    else if (key === 'ArrowUp') this.board = BoardService.rotateCurrentBlock(this.board);
    else if (key === 'Enter') this.board = BoardService.moveCurrentBlockDown(this.board, true);
  }
}

<div class="p-6 md:p-10 bg-blue-300 h-screen relative">
  <app-board [board]="board" />
  <app-game-over-dialog
    *ngIf="board.status === 'game-over'"
    [score]="board.score"
    (onRestart)="onRestart()"
  />
</div>
