// tetris-react/src/infrastructure/ui/app.tsx
import * as React from "react";
import { Board } from "../../../../domain/models/board";
import { BoardService } from "../../../../domain/services/services";
import { TetrisBoard } from "./board";
import { GameOverDialog } from "./game-over-dialog";

export function App() {
  const [board, setBoard] = React.useState<Board>(BoardService.getInitialBoard());

  // Move down the current block
  React.useEffect(() => {
    const timer = setInterval(() => {
      if (board.status === "game-over") return;
      setBoard((board) => BoardService.moveCurrentBlockDown(board));
    }, 1000);
    return () => clearTimeout(timer);
  }, [board.status]);

  // Keyboard event listener
  React.useEffect(() => {
    const keydownListener = ({ key }: KeyboardEvent) => {
      if (board.status === "game-over") return;

      if (key === "ArrowLeft") setBoard((board) => BoardService.moveCurrentBlockLeft(board));
      else if (key === "ArrowRight") setBoard((board) => BoardService.moveCurrentBlockRight(board));
      else if (key === "ArrowDown") setBoard((board) => BoardService.moveCurrentBlockDown(board));
      else if (key === "ArrowUp") setBoard((board) => BoardService.rotateCurrentBlock(board));
      else if (key === "Enter") setBoard((board) => BoardService.moveCurrentBlockDown(board, true));
    };

    document.addEventListener("keydown", keydownListener);
    return () => document.removeEventListener("keydown", keydownListener);
  }, [board.status]);

  return (
    <div className="p-6 md:p-10 bg-blue-300 h-screen relative">
      <TetrisBoard board={board} />
      {board.status === "game-over" && (
        <GameOverDialog score={board.score} onRestart={() => setBoard(BoardService.getInitialBoard())} />
      )}
    </div>
  );
}

// tetris-vue/src/infrastructure/ui/components/App.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

import TetrisBoard from "./TetrisBoard.vue";
import GameOverDialog from "./GameOverDialog.vue";
import { BoardService } from "../../../domain/services/services.ts";
import { Board } from "../../../domain/models/board";

const setBoard = (newBoard: Board) => {
  board.value = newBoard;
  tick.value++;
};

const board = ref<Board>(BoardService.getInitialBoard());
const tick = ref(0);

onMounted(() => {
  setInterval(() => {
    if (board.value.status === "game-over") return;
    setBoard(BoardService.moveCurrentBlockDown(board.value));
  }, 1000);
});

onMounted(() =>
  document.addEventListener("keydown", (event: KeyboardEvent) => {
    if (board.value.status === "game-over") return;

    if (event.key === "ArrowLeft") setBoard(BoardService.moveCurrentBlockLeft(board.value));
    else if (event.key === "ArrowRight") setBoard(BoardService.moveCurrentBlockRight(board.value));
    else if (event.key === "ArrowDown") setBoard(BoardService.moveCurrentBlockDown(board.value));
    else if (event.key === "ArrowUp") setBoard(BoardService.rotateCurrentBlock(board.value));
    else if (event.key === "Enter") setBoard(BoardService.moveCurrentBlockDown(board.value, true));
  })
);
</script>

<template>
  <div class="p-6 md:p-10 bg-blue-300 h-screen relative">
    <TetrisBoard :board="board" :key="tick" />
    <GameOverDialog
      v-if="board.status === 'game-over'"
      :score="board.score"
      :onRestart="() => setBoard(BoardService.getInitialBoard())"
    />
  </div>
</template>

<style scoped></style>
