// tetris-react/src/infrastructure/ui/board.tsx
import { BOARD_COLS, BOARD_ROWS, Board, BoardCellValue } from "../../../../domain/models/board";
import { BoardService } from "../../../../domain/services";
import { BoardScore } from "./board-score";

function mapCellValueToTailwindBackgroundColor(value: BoardCellValue): string {
  return {
    I: "bg-cyan-500",
    J: "bg-blue-500",
    L: "bg-orange-500",
    O: "bg-yellow-400",
    S: "bg-green-500",
    T: "bg-violet-500",
    Z: "bg-red-500",
    default: "bg-gray-300",
  }[value ?? "default"];
}

const boardStyles = {
  aspectRatio: `${BOARD_COLS}/${BOARD_ROWS}`,
  gridTemplateRows: `repeat(${BOARD_ROWS}, minmax(0, 1fr))`,
  gridTemplateColumns: `repeat(${BOARD_COLS}, minmax(0, 1fr))`,
};

function BoardCell({ value }: { value: BoardCellValue }) {
  return <div className={`rounded-sm text-xs ${mapCellValueToTailwindBackgroundColor(value)}`}></div>;
}

export function TetrisBoard({ board }: { board: Board }) {
  const cellValues = BoardService.getCellValues(board);

  return (
    <div className="h-full flex">
      <div className="shadow-xl w-auto h-full mx-auto rounded-lg bg-white relative">
        <div className="h-full grid grid-rows-20 grid-cols-10 gap-px p-2" style={boardStyles}>
          {cellValues.map((value, index) => (
            <BoardCell value={value} key={index} />
          ))}
          <BoardScore score={board.score} />
        </div>
      </div>
    </div>
  );
}

// tetris-angular/src/infrastructure/ui/components/board/board.component.ts
import { ChangeDetectorRef, Component, Input, OnChanges } from '@angular/core';
import { BOARD_COLS, BOARD_ROWS, Board, BoardCellValue } from 'src/domain/models/board';
import { BoardService } from 'src/domain/services/services';

const boardStyles = {
  aspectRatio: `${BOARD_COLS}/${BOARD_ROWS}`,
  gridTemplateRows: `repeat(${BOARD_ROWS}, minmax(0, 1fr))`,
  gridTemplateColumns: `repeat(${BOARD_COLS}, minmax(0, 1fr))`,
};

const getTailwindBackgroundColorFromCellValue = (value: BoardCellValue): string => {
  return {
    I: 'bg-cyan-500',
    J: 'bg-blue-500',
    L: 'bg-orange-500',
    O: 'bg-yellow-400',
    S: 'bg-green-500',
    T: 'bg-violet-500',
    Z: 'bg-red-500',
    default: 'bg-gray-300',
  }[value ?? 'default'];
};

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
})
export class BoardComponent implements OnChanges {
  @Input() board: Board = BoardService.getInitialBoard();
  public cellColors: string[] = [];
  boardStyles = boardStyles;

  constructor(private detectorRef: ChangeDetectorRef) {}

  ngOnChanges(): void {
    this.cellColors = BoardService.getCellValues(this.board).map((value: BoardCellValue) =>
      getTailwindBackgroundColorFromCellValue(value)
    );
    this.detectorRef.detectChanges();
  }
}

<div class="h-full flex">
  <div class="shadow-xl w-auto h-full mx-auto rounded-lg bg-white relative">
    <div
      class="h-full grid grid-rows-20 grid-cols-10 gap-px p-2"
      [style]="boardStyles"
    >
      <app-board-cell *ngFor="let color of cellColors" [color]="color" />
      <app-board-score
        [score]="board.score"
        class="absolute w-32 right-0 -mr-36 -mt-2 shadow-xl h-fit p-2 rounded bg-white text-center"
      />
    </div>
  </div>
</div>
